import numpy as np
array1 = np.array([[0, 1, 2], [2, 3, 4]]) 
array2 = np.array( [ [1,2], [3,4] ], dtype=float) 
array3 = np.zeros((2, 3))
array4 = np.ones((2, 3))
array5 = np.eye(3) 
array6 = np.arange(0, 10, 2) 
array7 = np.linspace(0, 10, 5) 
array8 = np.random.randint(0, 10, (3, 3))
print(array1, "\n")
print(array2, "\n")
print(array3, "\n")
print(array4, "\n")
print(array5, "\n")
print(array6, "\n")
print(array7, "\n")
print(array8, "\n")
